# Домашная работа 2

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.
4. Пришлите на почту *ml-teachers* ссылку на этот файл в вашем репозитории.
5. В теме письма указать `ML Homework #2: Name Surname`. Если тема будет неправильная, то задание не будет проверено.

**Дедлайн: 3.11.2017 6:00 OMSK**

## Numpy

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

1) Импортировать numpy и написать версию

In [2]:
import numpy as np
np.__version__

'1.13.1'

2) Создать нулевой вектор размера 10

In [3]:
zero10 = np.zeros(10)

3) Создать вектор заполненный 7-ами размера 7

In [4]:
sevenSeven = np.full(7,7)
sevenSeven

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [5]:
even = np.arange(102)[10:101:2]
even

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [6]:
r = np.random.random_sample(10)
print(r)
print(r[::-1])

[ 0.24782187  0.19287337  0.75572115  0.44029916  0.51048235  0.78395195
  0.14404547  0.23257002  0.92101895  0.77030759]
[ 0.77030759  0.92101895  0.23257002  0.14404547  0.78395195  0.51048235
  0.44029916  0.75572115  0.19287337  0.24782187]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [7]:
a = np.arange(9).reshape(3,3) + 1
#опечатка в задании? 10 числе от 0 до 9 , 9 ячеек в 3х3
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [8]:
np.concatenate( ( np.full((4,1),0), np.concatenate((np.eye(3),np.full((1,3),0)),axis = 0)),axis=1)

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [9]:
np.diag([-6,-5,-4,-3]) + 7

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
np.full((5,5),np.arange(5))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [11]:
a = np.random.random_sample((10,10))
#a = np.arange(4).reshape(2,2)
(a.T - a.mean(axis = 1)).T

array([[ 0.09719129,  0.15574737,  0.54955382, -0.31092034,  0.39853328,
        -0.1528962 , -0.23542331,  0.04172758, -0.33990766, -0.20360584],
       [ 0.37198355, -0.38631496,  0.57956341, -0.40821763,  0.03466589,
        -0.2257701 , -0.33298659,  0.30738372,  0.20066855, -0.14097584],
       [-0.58415693,  0.00490223, -0.53963854,  0.17657777,  0.12279032,
        -0.12474436,  0.30906167,  0.39679824, -0.00224911,  0.2406587 ],
       [-0.49706607,  0.12179332,  0.19276684, -0.36678653,  0.13396728,
        -0.32466083, -0.15237724,  0.44275026,  0.26407505,  0.18553792],
       [-0.41991714,  0.35836877, -0.16025281,  0.20986869, -0.08047487,
        -0.168707  ,  0.41383045, -0.47108904,  0.03623537,  0.28213759],
       [-0.45725551,  0.24479369,  0.28980965,  0.17385003, -0.45625928,
        -0.20409459,  0.09206103, -0.05712259,  0.09033555,  0.28388204],
       [ 0.1724003 , -0.27683471, -0.27246826,  0.39735827, -0.24957093,
         0.32191346,  0.38347652,  0.07854678

12) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца

In [17]:
a = np.random.random_sample((10,10))
a = np.arange(4).reshape(2,2)
#np.median(a,axis = 1)
(a - np.median(a,axis = 0))

array([[-1., -1.],
       [ 1.,  1.]])

13) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.

In [32]:
a = np.random.random_sample((5,5))
a = np.concatenate( (a, a.max(axis=1).reshape(5,1) ),axis = 1)
a = np.concatenate( (a, a.min(axis=1).reshape(5,1) ),axis = 1)
a

array([[ 0.48749587,  0.97522335,  0.52094374,  0.47831184,  0.19210619,
         0.97522335,  0.19210619],
       [ 0.99324109,  0.36904734,  0.24399561,  0.4120481 ,  0.62229136,
         0.99324109,  0.24399561],
       [ 0.75326051,  0.75605515,  0.97216905,  0.35578541,  0.71945719,
         0.97216905,  0.35578541],
       [ 0.35430599,  0.78643074,  0.40054676,  0.31068186,  0.75462882,
         0.78643074,  0.31068186],
       [ 0.19655969,  0.00534338,  0.99428275,  0.7750684 ,  0.8647397 ,
         0.99428275,  0.00534338]])

14) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.

In [42]:
#тоже опечатка в задании , не сходятся размерности 51 против 2 по 25
a = np.arange(50)+1
b = np.matrix(a[::2].reshape(5,5))
c = np.matrix(a[1::2].reshape(5,5))
MP = b*c
print(MP)
print(MP.I)

matrix([[ -6.21359223e-02,  -4.73786408e-02,  -7.33007752e+11,
           1.46601550e+12,  -7.33007752e+11],
        [  8.94517934e+12,  -2.38538116e+12,  -1.75921860e+13,
           6.55979819e+12,   4.47258967e+12],
        [ -1.31195964e+13,  -7.15614348e+13,   1.77387876e+14,
          -8.76130621e+13,  -5.09378268e+12],
        [ -5.96345290e+11,   1.50279013e+14,  -2.99067163e+14,
           1.49682668e+14,  -2.98172645e+11],
        [  4.77076232e+12,  -7.63321971e+13,   1.40004481e+14,
          -7.00954193e+13,   1.65237341e+12]])

15) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [49]:
a = np.zeros( (8,8) ) 
a[::2,1::2] = 1
a[1::2,::2] = 1
a

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

## Pandas

#### Полезная литература

- http://pandas.pydata.org/pandas-docs/stable/10min.html
- https://pandas.pydata.org/pandas-docs/stable/indexing.html
- https://pandas.pydata.org/pandas-docs/stable/missing_data.html

В этом задании мы с вами рассмотрим датасет [Adult Data Set](https://archive.ics.uci.edu/ml/datasets/Adult).
Основывается он на данных переписи населения 1994 года в США.

Расшифровка содержимого колонок:

- age: continuous. 
- workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked. 
- fnlwgt: continuous. sampling weight, more here: SIPP Weighting.
- education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool. 
- education-num: continuous. 
- marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse. 
- occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces. 
- relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried. 
- race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black. 
- sex: Female, Male. 
- capital-gain: continuous. Income from investment sources, apart from wages/salary.
- capital-loss: continuous. Losses from investment sources, apart from wages/salary.
- hours-per-week: continuous. 
- native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

In [14]:
%matplotlib inline
import pandas as pd
pd.__version__

'0.20.3'

In [51]:
df = pd.read_csv('adult.csv.gz', compression='gzip', na_values='?')
df.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90       NaN   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66       NaN  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                NaN  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                NaN      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

1) Выведите последние 10 элеметнов датасета  

2) Сколько колонок и сколько строк в этом датасете?

3) Какие типы данных у элементов этого датасета?

4) Какие признаки имеют пропуски?

5) Как вы думаете, с чем связаны пропуски этих значение. Напишите развернутый ответ в ячейке ниже.

**ответ:**

6) Какие и сколько различных рабочих классов `workclass` представлено в выборке?

7) Какой средний возраст женщин и мужчин?

8) Постройте гистограмму(bar) распределения образования людей (education)

9) Каковы средние значения и среднеквадратичные отклонения возраста тех, кто получает более 50K в год (признак salary) и тех, кто получает менее 50K в год?

10) Правда ли, что люди, которые получают больше 50k, имеют как минимум высшее образование? (признак education - Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters или Doctorate)

11) Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак marital-status)? Женатыми считаем тех, у кого marital-status начинается с Married (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.

12) Посчитайте среднее время работы (hours-per-week) зарабатывающих мало и много (salary) для каждой страны (native-country).

13) Постройте сводную таблицу для сравнения уровня образования и разницы между capital.gain и capital.loss (то есть пассивный доход). Сделайте так, чтобы `capital.gain - capital.loss` создали не больше 10 разных уникальных значений.

14) Женщины из каких стран получают в среднем большую зарплату (>50K) чаще.

15) Создайте случайную колонку - `magic_salary`, которую нужно будет вычислить следующим образом: если зарплата небольшая (<50K), тогда случайно выберите число из диапазона [0,50]. Если зарплата выше 50K тогда из диапазона [51, 200]. Посчитайте среднюю зарплату в час для групп людей с одни уровнем образования на основе нашей случайной колонки `magic_salary`